[package]
name = "aptos_vibes"
version = "1.0.0"
authors = ["Aptos Vibes Team"]

[addresses]
aptos_vibes = "0x5bd3338c9f09619c16a5207af405b84e98d041c8194ea90c2243be7dba513423"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "b9f89a1"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "b9f89a1"
subdir = "aptos-move/framework/aptos-stdlib"

[dev-dependencies] 