[package]
name = "aptos_vibes"
version = "1.0.0"
authors = ["Aptos Vibes Team"]

[addresses]
aptos_vibes = "_"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "b9f89a1"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "b9f89a1"
subdir = "aptos-move/framework/aptos-stdlib"

[dev-dependencies] 